services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./var:/app/var
      - ./backend:/app/backend
    env_file: .env
    restart: unless-stopped
